### ISSUE TITLE
AFK Mouse Move 0,0

### ISSUE THREAD

**Issue by Loka0oo** [9-9-9-9/Bit-Heroes-bot#101]
Could remove the mouse move 0,0 it is very inconvenient sometimes, put the AFK function similar to the RERUN function that does not have this mouse move 0,0

**Comment by daredoes** [comment]
Tell me about it. I'll disable/move this to config soon ideally.

**Comment by daredoes** [comment]
This is solved now, but not yet released for EZ consumption
