### ISSUE TITLE
Bot Dont Work in New Steam Version

### ISSUE THREAD

**Issue by Loka0oo** [9-9-9-9/Bit-Heroes-bot#102]
Bot Steam Dont work i new steam version.

Windows 11
Steam Version:1679113038 
Steam API:v020

Bit Heroes Version:2.4.460b93

**Comment by CoaltCross** [comment]
Will this be updated to play with the lastest raid tier 20?

**Comment by Loka0oo** [comment]
> Will this be updated to play with the lastest raid tier 20?

I'm playing on another tier, after steam updates my bot is no longer recognizing any icon, with no AFK, RERUN, PVP, FISHING function. Anything

**Comment by 9-9-9-9** [comment]
Hello friends, I already quited game for more than 6 months so this topic will be leave open for the next maintainer, or just...die

**Comment by daredoes** [comment]
@Loka0oo its an issue with how Windows 11 detects the window. Figured it out. I'll try to push an updated version soon

**Comment by daredoes** [comment]
@Loka0oo try with 3.7.0
