### ISSUE TITLE
steam rerun isn't working 

### ISSUE THREAD

**Issue by Kraker01** [9-9-9-9/Bit-Heroes-bot#16]
Iàm experiencing this error when using Steam rerun

Using 'steam' profile which supports 800x480 game resolution
****** IMPORTANT ****** IMPORTANT ******
** WARNING ** You must move the Bit Heroes game's window to top left corner of your screen or provide exactly screen offset into the 'offset.screen.x & y' keys
** WARNING ** Your Bit Heroes game window must be 800x480. You can check it by open Settings, see the Windowed option
****************************************
Going to load configuration from user-config.properties
java.lang.IllegalArgumentException: input == null!
        at javax.imageio.ImageIO.read(Unknown Source)
        at bh.bot.common.utils.ImageUtil.loadImageFileFromResource(ImageUtil.java:14)
        at bh.bot.common.types.images.BwMatrixMeta.load(BwMatrixMeta.java:211)
        at bh.bot.app.AbstractApplication.run(AbstractApplication.java:51)
        at bh.bot.Main.main(Main.java:76)
input == null!

Using latest Steam, Windows 10 64

**Comment by 9-9-9-9** [comment]
I see, I made automatically reactive the red Auto button but forgot the Steam profile.
Anyway, why dont you use the mini-client? The 800x480 might not compatible all the time and usually not get support

**Comment by Kraker01** [comment]
Yesterday i used rerun in Mini client for 1000 repeats. I got a out of memory error and Chrome mini Windows Just hanged.

I wanted to try standalone game in Steam Just to verify if it's a PC related problem or Chrome problem

**Comment by 9-9-9-9** [comment]
Its chrome problem man. I also got it. Btw there is a bug from Bit Heroes itself, when you level up, the current energy set to max energy (eg 0 to 300, 100 to 300, 3000 to 300 no matter how much current energy you have). So don't drink too much energy at one

**Comment by 9-9-9-9** [comment]
@Kraker01 hey man, it's fixed at [v1.2.6](https://github.com/9-9-9-9/Bit-Heroes-bot/releases/tag/release-1.2.6)
Tested on Windows 7 64bit + Steam

Please let me know if it works so I can close this issue

**Comment by Kraker01** [comment]
Tested now, working fine

**Comment by 9-9-9-9** [comment]
@Kraker01 bro, [new release 1.4.0](https://github.com/9-9-9-9/Bit-Heroes-bot/releases/tag/release-1.4.0) contains many good change
