### ISSUE TITLE
Trials not working

### ISSUE THREAD

**Issue by Kraker01** [9-9-9-9/Bit-Heroes-bot#23]
Windows 10, latest (great) version 1.4.0

Trials not working, here's the error:
Image is not available: game-images_steam_labels_attendable-places_trials-tp, profile steam

**Comment by 9-9-9-9** [comment]
Hi, fixed it, thank you
[Download 1.4.1 here](https://github.com/9-9-9-9/Bit-Heroes-bot/releases/tag/release-1.4.1)
