### ISSUE TITLE
Expeditions not working

### ISSUE THREAD

**Issue by Kraker01** [9-9-9-9/Bit-Heroes-bot#24]
Windows 10 64, latest version (1.4.0)

Expeditions aren't working, here's the error:

Image is not available: game-images_steam_labels_attendable-places_expedition-tp, profile steam

**Comment by 9-9-9-9** [comment]
Hi, fixed it, thank you
[Download 1.4.1 here](https://github.com/9-9-9-9/Bit-Heroes-bot/releases/tag/release-1.4.1)
