### ISSUE TITLE
Unable to access jarfile BitHeroes.jar

### ISSUE THREAD

**Issue by Despa1r** [9-9-9-9/Bit-Heroes-bot#45]
Hello.
After building, i tried to run steam version of bot by using steam.bot.bat and got this mistake.

C:\Users\ierun\Bit-Heroes-bot-release-1.7.2>call _.bat  --steam

C:\Users\ierun\Bit-Heroes-bot-release-1.7.2>java -jar BitHeroes.jar --steam
Error: Unable to access jarfile BitHeroes.jar

C:\Users\ierun\Bit-Heroes-bot-release-1.7.2>goto L_EXIT

C:\Users\ierun\Bit-Heroes-bot-release-1.7.2>pause
Для продолжения нажмите любую клавишу . . .

**Comment by 9-9-9-9** [comment]
Hi, you was downloaded the source code file which does not contains compiled jar file.

You must download the zip file which has '99bot' part in it's name and file size should be around 4mb

![Screenshot_20211001-055635_GitHub.jpg](https://user-images.githubusercontent.com/49741222/135540601-7b2f38e2-ce2b-4040-868f-47c013974553.jpg)

**Comment by Despa1r** [comment]
Ok, thx.
