### ISSUE TITLE
Unable to prepare Mini-Chrome

### ISSUE THREAD

**Issue by Kraker01** [9-9-9-9/Bit-Heroes-bot#5]
I've followed your instructions, but when I copy/paste the commands into Console Tab (into developers tools) i receive a "undefined" response.

I tried to launch your script using --debug flag, this i what I get:
C:\Users\Marco\Documents\GitHub\Bit-Heroes-bot>java -jar BitHeroes.jar rerun 10 --debug --img
Going to load configuration from user-config.properties
Enabled debug messages
Telegram is disabled due to missing or invalid configuration
Enabled saving debug images
Loop: 10
Mouse move cursor
Not found, repeat
Not found, repeat
Not found, repeat
Not found, repeat

(got X,Y coordinates using your Screenshot+Paint trick)

**Comment by 9-9-9-9** [comment]
> I've followed your instructions, but when I copy/paste the commands into Console Tab (into developers tools) i receive a "undefined" response.

Hi,
### That happens when you didn't login
![guest](https://drive.google.com/uc?export=view&id=1B1q2nKadd-KPDwZBc3HbTIg8KlESpev6)

### You must login using your Kongregate account first and then paste it later
![user logged in](https://drive.google.com/uc?export=view&id=1bEKpE-tGrtEWgiN867l9hNIYAbtLlK3-)

**Comment by 9-9-9-9** [comment]
> I tried to launch your script using --debug flag, this i what I get:
> C:\Users\Marco\Documents\GitHub\Bit-Heroes-bot>java -jar BitHeroes.jar rerun 10 --debug --img
> Going to load configuration from user-config.properties
> Enabled debug messages
> Telegram is disabled due to missing or invalid configuration
> Enabled saving debug images
> Loop: 10
> Mouse move cursor
> Not found, repeat
> Not found, repeat
> Not found, repeat
> Not found, repeat
> 
> (got X,Y coordinates using your Screenshot+Paint trick)

I assume you configured the mini client successfully and want to click ReRun button.

I have to tell this first, the **ReRun** app **only** supports click ReRun button, which mean, you have to get in Dungeon/Raid yourself, make it Auto attack and run... and when the ReRun button appears, the bot do it job is Click it to let you do the Dungeon/Raid again.

If you already understood about it and still having trouble, please give me a screenshot, and your `screen.offset.x` and `screen.offset.y` configuration

**Comment by 9-9-9-9** [comment]
One more thing, you are using Windows 10 or Windows 7? 32 bit or 64 bit?

**Comment by Kraker01** [comment]
Mini client is correctly set up
Offset has been correctly set up (10, 0)
I'm using Windows 10 64 bit

Rerun isn't working (i left the mini client open on a finished dungeon, game language is set to English)

**Comment by Kraker01** [comment]
![Cattura](https://user-images.githubusercontent.com/20519780/131232187-a5fb8f0e-4ccc-49d8-af13-6c52b1c3a6b8.PNG)

**Comment by 9-9-9-9** [comment]
@Kraker01 im pretty sure you did it wrong somewhere
The `10,0` value is absolutely wrong. Why?
Its `x` and `y` while `x` stands for how many pixel from most left of your screen until the first pixel of the game screen.
and the `y` stands for how many pixel from top of your screen until the first pixel of the game screen.
You see there is a border/a title bar of the game window, which has the name *Bit Heroes*, it visible right there so the `y` value can not be `0`

Based on [this wiki](https://github.com/9-9-9-9/Bit-Heroes-bot/wiki/Basic-setup):
> On Windows 10, usually `x=8` and `y=31` when using mini client of Google Chrome

So I suggest you try
`offset.screen.x=8`
`offset.screen.y=31`
and try again

**Comment by 9-9-9-9** [comment]
@Kraker01 btw I suggest you should install the [latest release version](https://github.com/9-9-9-9/Bit-Heroes-bot/releases)

**Comment by Kraker01** [comment]
Downloaded latest release 
Set up from scratch 
Set up correct x,y values (based on Game pixels and NOT window pixels)

Launched, it's working smooth

**Comment by 9-9-9-9** [comment]
nice, upcoming release contains new app `afk`, help you do world boss, gvg/invasion trials/gauntlet while afk

**Comment by 9-9-9-9** [comment]
@Kraker01 one more note, you can reduce value of `tolerant.position=50` in your `user-config.properties` once you configured the screen offset correctly. Suggested value is `8`, so modify it to `tolerant.position=8`. It helps increase bot's performance
