### ISSUE TITLE
[Bug] Selecting PVP team

### ISSUE THREAD

**Issue by Dumi-07** [9-9-9-9/Bit-Heroes-bot#61]
**Describe the bug**
While bot is on AFK mode, it picks just first team for PVP even i have in settings to be the las team(4).

**To Reproduce**
Mode?------------AFK
Steps to reproduce the behavior?---------Start bot on AFK mode, let it do the work.

**Expected behavior**
I expected to chose last team(4) on PVP.

**Screenshots**

** Environment: **
 - OS: Windows 10
 - Client Steam
 - Version 2.5.0

**Comment by 9-9-9-9** [comment]
@Dumi-07 hi, it's not a bug. There is a yellow and red warning message:

> ** WARNING ** about selecting PVP target feature, to prevent wrong targeting and un-expected loss on other target-selectable ranking like GVG... (which having the same target-selection method), while doing AFK, this feature works and only works when bot itself attends to PVP by selecting the PVP icon (top left of game screen). That means if you select the PVP icon yourself or enter PVP before bot click etc.., it only select the first line as target as default
