### ISSUE TITLE
ReRun issue (bot click button wrongly)

### ISSUE THREAD

**Issue by GibsonYT** [9-9-9-9/Bit-Heroes-bot#65]
**Describe the bug**
ReRun function isn't working correctly

**To Reproduce**
I run the command when the rerun button is visible after completing a dungeon, but the cursor goes straight up away the game and stays there without doing anything, meanwhile the cmd says that it is doing the correct job and the loop starts to decrease the number but never touches rerun button.

**Expected behavior**
The bot should press the rerun button and the cursor shouldn't go straight up

** Environment: **
 - WIndows 10 running Steam Bit Heroes at version 2.3.206 at 800x480
 
**Additional context**
I tested fishing in the exact same resolution and without changing the game frame position and it worked perfectly

**Comment by 9-9-9-9** [comment]
Hi @GibsonYT this issue require debugging so I need to have the device with this issue on hand to check. Im sorry I can't help with this.

**Comment by GibsonYT** [comment]
Can i help with something?

**Comment by 9-9-9-9** [comment]
@GibsonYT today an user got simular issue and the reason was about screen scale ratio. Please set it to 100% (original, no scale)

Read here 👉 https://www.windowscentral.com/how-set-custom-display-scaling-setting-windows-10

**Comment by GibsonYT** [comment]
Very thanks!!!! Now works!!!

**Comment by 9-9-9-9** [comment]
Glad to hear

**Comment by 9-9-9-9** [comment]
@GibsonYT btw, plz give this repo a Star just by clicking the Star button at top right of this page
