### ISSUE TITLE
Update for R17 

### ISSUE THREAD

**Issue by Tactlesshail** [9-9-9-9/Bit-Heroes-bot#68]
when will there be an update for the new current teir?

**Comment by 9-9-9-9** [comment]
It's should be R15 for T18, right? [Here you go](https://github.com/9-9-9-9/Bit-Heroes-bot/releases/latest)

**Comment by 9-9-9-9** [comment]
Btw @Tactlesshail next time don't wait for new update, just ask me for new update whenever new tier comes, it's kinda easy to update but I'm not a latest tier so I don't pay attention, ok?

**Comment by Tactlesshail** [comment]
Yes my bad, thanks

Sent via the Samsung Galaxy S21 5G, an AT&T 5G smartphone
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
