### ISSUE TITLE
mini-client

### ISSUE THREAD

**Issue by kahunadae** [9-9-9-9/Bit-Heroes-bot#71]
Hello
Im unable to generate "mini-client" but everytime i start client.bat it always says " Unable to generate mini-client!!! " even after i checked my user-config and i think i did everything right as the "prepare-mini-chrome-client" says.
There is 98% chance i just fvcked up but after this time i dont know what can i do different.

**Comment by 9-9-9-9** [comment]
Hello, I need more log, I can't do anything with a simple sentence "Unable to generate mini-client!!!".

Remember to remove sensitive information (if any)

@kahunadae
____
I guess the Chrome location is not correctly set
> user-config.properties

> #Google Chrome path, for Windows only
> external.application.chrome.path=C:\\\\Program Files (x86)\\\\Google\\\\Chrome\\\\Application\\\\chrome.exe

You need to edit the above path to match location of chrome.exe in your computer

**Comment by kahunadae** [comment]
My apology @9-9-9-9  i hope it did not sounded rude.
I think my path for chrome.exe is correct i was even tried to set it both ways with " \ " and " \\ " dont know if that have some effect on it.
![notepad](https://user-images.githubusercontent.com/104935349/166907180-d5590456-e61c-4570-a382-546f61a76e1d.png)

**Comment by 9-9-9-9** [comment]
Damn, you configured wrongly.
Remove the # in the beginning of the following lines:

> #1.game.kong.user.id
> #1.game.kong.user.name
> #1.game.auth.token
> #external.application.chrome.path

They MUST look like this:
> 1.game.kong.user.id
> 1.game.kong.user.name
> 1.game.auth.token
> external.application.chrome.path

**Comment by kahunadae** [comment]
I don't believe how stupid am.. My apology for your wasted time with me. THANKS a lot! works fine.
