### ISSUE TITLE
[QUESTION] Mini Chrome - Out of memory

### ISSUE THREAD

**Issue by JacsonF** [9-9-9-9/Bit-Heroes-bot#75]
Hello, 
I would like to share a problem I came across grinding:

After some time doing raid or any other resource I get this error, my pc has 24g of ram memory, so I found it strange, I did a search on this problem, honestly I didn't find a solution, from what I understood this would be a problem that the game developers would have to deal with.

I would like to know if anyone has gone through this, and if there is any way to get around this problem.

I'm using:
-  Lubuntu 22.04
-  Virtualizing with virt manager with antiX-21 OS each VM has 6G of ram

![image](https://user-images.githubusercontent.com/11538534/174165666-02db81a1-f36f-4c9b-bba7-b4b1c637ca21.png)

Just to top it off, the problem occurs both on the VM and directly on my machine.
I already did a test running only the mini-chrome and nothing else on my pc, even so, after a while I get this error.

**Comment by 9-9-9-9** [comment]
Ya this is truly annoying! It happens to me after 3-4 hours in whatever my device was. Wanna know if any1 can work around this.

>  From what I understood this would be a problem that the game developers would have to deal with

Agree, and probably +chrome dev

**Comment by JacsonF** [comment]
It's not a definitive solution but for now it's helping me grind :
I migrated my VMs to windows and created a steam account for my all my accounts so I can get out of the chrome problem.

As time goes by, the loading becomes slower, but you avoid the memory overflow problem, what I've been doing is restarting after a while.

As a reminder, I'm only using this approach for grinding, where I want to enjoy as much time as possible.

**Comment by 9-9-9-9** [comment]
Steam can last for 6-8 hours before app crash

**Comment by gnidnE** [comment]
Setting a frame cap can help mitigate this, otherwise the frame rate is uncapped and can run in the 1000s.
