### ISSUE TITLE
[Bug] ...

### ISSUE THREAD

**Issue by rulo6666** [9-9-9-9/Bit-Heroes-bot#76]
The AFK option does not work:

If you put 255 for an All Run, it gets stuck there. In the screenshot URL its visible in the right side.

And its supossed to run the regen once you set it up.

**Screenshots**
(_image source is not safe so I removed_)

** Environment: **
- windows 10
 - Client WEB
 - Version (2.9.2)

I dont know if I am doing something wrong, I think its all ok, but still doesn't work.
The config is already set, twice thinking I was setting up wrongly.

**Comment by gnidnE** [comment]
Try pressing "Enter" again after you input "255". It should then ask you to select a profile.

**Comment by 9-9-9-9** [comment]
It does works for months. It didn't work for you bc you didn't use it correctly bro.

Btw please upload your image to google drive or another safe place. I won't click in strange urls

**Comment by 9-9-9-9** [comment]
I suggest you use [command line](https://github.com/9-9-9-9/Bit-Heroes-bot/blob/master/AFK.steam.bat)

**Comment by rulo6666** [comment]
> Try pressing "Enter" again after you input "255". It should then ask you to select a profile.



Does not work :/ I'll add how it looks in a Google Drive link. Once I click "Enter" it just take me back to the previous question.

https://drive.google.com/file/d/12_EllS8NJLsQ5JIApadakUESld9GV6WN/view?usp=sharing



I hope you can help me 👍

**Comment by rulo6666** [comment]
> It does works for months. It didn't work for you bc you didn't use it correctly bro.
> 
> Btw please upload your image to google drive or another safe place. I won't click in strange urls

Here is how it looks like once I press "Enter" after "255", It just take me back to the previous question. I know I'm not an experte, but I dont know if I'm doing it wrong, if you can help me I'll be very grateful 


https://drive.google.com/file/d/12_EllS8NJLsQ5JIApadakUESld9GV6WN/view?usp=sharing

**Comment by rulo6666** [comment]
> I suggest you use [command line](https://github.com/9-9-9-9/Bit-Heroes-bot/blob/master/AFK.steam.bat)



> I suggest you use [command line](https://github.com/9-9-9-9/Bit-Heroes-bot/blob/master/AFK.steam.bat)

Im sorry :( but how can I use it? Where do I need to paste it?

**Comment by 9-9-9-9** [comment]
> > It does works for months. It didn't work for you bc you didn't use it correctly bro.
> > Btw please upload your image to google drive or another safe place. I won't click in strange urls
> 
> Here is how it looks like once I press "Enter" after "255", It just take me back to the previous question. I know I'm not an experte, but I dont know if I'm doing it wrong, if you can help me I'll be very grateful
> 
> https://drive.google.com/file/d/12_EllS8NJLsQ5JIApadakUESld9GV6WN/view?usp=sharing

Haha I wrote clearly: `To finish input, just enter without supply a number`. So you just need to [255 + Enter + Enter], there you go
