### ISSUE TITLE
Unable to run bot as administrator, also cannot select desired resolution.

### ISSUE THREAD

**Issue by Nikko1217** [9-9-9-9/Bit-Heroes-bot#77]
Hello, I keep running into an error running the steam version of the game. I cannot select the desired resolution and it recommends running the bat file as an administrator to give it permission to change the resolution itself. It flashes open but instantly closes itself when ran as an admin

**Comment by 9-9-9-9** [comment]
I guess you didn't have java installed

You can
1. Run a cmd (press Window, type `cmd`, right click and choose run as administrator)
2. `cd` into the bot folder
3. type `steam.bot.bat` and enter and tell me which error it said
