### ISSUE TITLE
[Bug] ... (Post resize) JNA detect invalid screen size of Steam client! Expected 800x520 but found 799x520       

### ISSUE THREAD

**Issue by VonShleifin** [9-9-9-9/Bit-Heroes-bot#79]
**Describe the bug**

**To Reproduce**
Mode? (AFK/ReRun/...)
Steps to reproduce the behavior?

**Expected behavior**

**Screenshots**

** Environment: **
 - OS: (Windows 7/Windows 10/Ubuntu 20)
 - Client (Steam/Mini-client/Web)
 - Version (2.4.0/2.3.0/...)

**Additional context**

**Comment by VonShleifin** [comment]
Im selecting the things I want bot to do (world boss, 100m loops, etc), this my first time using this too, nothing happens and it tells me the window size isn't right. How do I fix it?

**Comment by 9-9-9-9** [comment]
Do you have a 4k monitor? Change the resolution to 1920. I have no idea why this fixes the issue but one of my friend faced with this and that's how he resolved the problem.

**Comment by 9-9-9-9** [comment]
You can also try to run bot with administrator permission to see if it works
