### ISSUE TITLE
Bot no longer working since new BH update November 16th, 2022

### ISSUE THREAD

**Issue by FriedNoodles123** [9-9-9-9/Bit-Heroes-bot#80]
Hello! The BH steam version got updated and now the steam bot no longer works :<

**Comment by 9-9-9-9** [comment]
Mini client doesn't work also, as I know

Great, no bot => no farm => won't buy packs => not wasting money

**Comment by FriedNoodles123** [comment]
Yup! The bot was so good, unfortunately I won't be spending too much on it now haha

**Comment by 9-9-9-9** [comment]
#81 fixed Fishing and ReRun
FYI

**Comment by FriedNoodles123** [comment]
Let's go! Thank you for your hard work

**Comment by 9-9-9-9** [comment]
#82 fixed Raid and PVP
FYI

**Comment by 9-9-9-9** [comment]
[v3.0.0](https://github.com/9-9-9-9/Bit-Heroes-bot/releases/tag/release-3.0.0) has just been released

Now almost functions are back to work as normal, except events which aren't on going (eg: Gauntlet, Invasion, Expedition)

Will publish other release for those if needed.

Cheer

**Comment by FriedNoodles123** [comment]
Thank you :]

**Comment by 9-9-9-9** [comment]
[v3.1.0](https://github.com/9-9-9-9/Bit-Heroes-bot/releases/tag/release-3.1.0) fixed Invasion and Gauntlet, FYI
