### ISSUE TITLE
Detected 'Defeated' State

### ISSUE THREAD

**Issue by FriedNoodles123** [9-9-9-9/Bit-Heroes-bot#90]
Hello!

Additional Note: I have ran "Rerun" before with no issues, but with the constant updates from BH; there's a possibility it could have broken

For the "ReRun" option, which is the only one that i'm having problems with, it's not running correctly.
It will go for about 6-7 loops and then state **Warning** Detected 'Defeated' State" which is weird to me because I am using insanely OP friends to farm on my alt. I'm running T2 D1 "Yeti Dungeon". Don't have this issue with any other function. Do i need to add a flag or what else should i do?

Thank you for your time!
![b1 help](https://user-images.githubusercontent.com/118333872/210154590-e5d4cff3-04ae-4c2b-be9d-d59fb8489861.png)

**Comment by 9-9-9-9** [comment]
Hi, sometime I see it but was too lazy to fix it 👯
