### ISSUE TITLE
[Bug] Ubuntu 22 LTS - Image Scan is distorted

### ISSUE THREAD

**Issue by daredoes** [9-9-9-9/Bit-Heroes-bot#94]
**Describe the bug**
When running the bot in an Ubuntu 22 LTS VM having installed `apt install openjdk-8-jre xdotools -y` the images scanned by the bot are heavily distorted, and unable to match properly.

**To Reproduce**
Download Ubuntu 22 LTS
Install into Virtual Box VM
run `sudo apt-get install openjdk-8-jre xdotools -y`
download the latest bot
setup a chrome client
issue a command with the debug and image flags
see the corrupted image

**Expected behavior**
The image scans produce images of the game

**Screenshots**
![image](https://user-images.githubusercontent.com/6538753/215351139-78d7d4f1-313a-4969-b10a-f2b86cce1cb7.png)

** Environment: **
 - OS: Ubuntu 22
 - Client: Mini-Client
 - Version: 3.6.0

**Additional context**

**Comment by 9-9-9-9** [comment]
Why don't you use Windows 7 with Steam? It's pretty lightweight

Around 1 year ago, I have tried to use Ubuntu VM guess and had blank capture problem. Most research kinda about configuration and driver,... and I was failed to resolve, unfortunately

**Comment by daredoes** [comment]
Windows 7 VM works. Avoiding steam because I don't want to login. I love the mini-client though.

**Comment by 9-9-9-9** [comment]
wont fix
