### ISSUE TITLE
[Bug] mini-client only doing wb and raid on -afk

### ISSUE THREAD

**Issue by Alexz1n** [9-9-9-9/Bit-Heroes-bot#95]
**Describe the bug**
from 3.5.1 onwards my mini client only do wb and raid, even if a put only pvp option it does nothing. Steam works fine

**To Reproduce**
insert any mode that isn't wb and raid, it does nothing. put wb/raid it do fine.

**Expected behavior**
Do everything like steam version.

** Environment: **
 - Windows 10
 - Mini-client
 - 3.5.1 - 3.6.0

**Comment by 9-9-9-9** [comment]
@daredoes do you have any idea?

**Comment by 9-9-9-9** [comment]
@Alexz1n does it back to work when you revert to v3.4.2?

**Comment by Alexz1n** [comment]
@9-9-9-9 yes it worked, then i tried 3.6.0 again and magically started working too. Haven't closed the game. Just tried 3.4.2, then 3.6.0 on same instance as I tried 3.6.0 earlier.

**Comment by 9-9-9-9** [comment]
Please close the instance and start it again with 3.6.0. If it work gracefully, we can close this issue

**Comment by Alexz1n** [comment]
It seems ok now. No idea what happened, some days already with this problem. If happens again I will contact again so we can see what's happening. Thanks for the time.
